name: Check Available Runners
on:
  push:
    branches:
      - '*'

jobs:
  check-runners:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Runner OS
        run: echo "The runner is using ${{ runner.os }} operating system."

      - name: Check Runner Labels
        run: echo "The runner has the following labels: ${{ runner.labels }}"

      - name: List Available Runners
        run: |
          echo "Available runners:"
          github-runner list
