name: build-and-deploy-sql

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build SQL project
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      run: choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional"
      shell: cmd

    - name: Build database project
      working-directory: MyDatabaseProject # Adjust the path based on your project structure
      run: msbuild MyDatabase.sqlproj /p:Configuration=Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: db
        path: db

  deploy:
    name: Deploy to test environment
    runs-on: arc-runner-set2

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: db
        path: db

    - name: Install SqlPackage
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlpackage

    - name: Remove security folder from .dacpac
      run: |
        sqlpackage /a:Script /sf:db/AdvWorkFlow.dacpac /p:ExcludeObjectType=Users > db/AdvWorkFlow_NoSecurity.dacpac

    - name: Deploy Package on Test Environment
      run: |
        sqlpackage /a:Publish /sf:db/AdvWorkFlow_NoSecurity.dacpac /tsn:$DB_HOST,$DB_PORT /tdn:$DB_TARGET /tu:$DB_USERNAME /tp:$DB_PASSWORD /p:BlockOnPossibleDataLoss=False
