name: build-workflow

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    name: Deploy to test environment
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Mono and MSBuild
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete

    - name: List Files and Folders in Current Directory
      run: |
        pwd
        ls -la

    - name: Build database project
      working-directory: src/AdvWorkFlow # Adjust the path based on your project structure
      run: msbuild AdvWorkFlow.sqlproj /p:Configuration=Release

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: db
        path: db

    - name: Install SqlPackage
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlpackage

    - name: Remove security folder from .dacpac
      run: |
        sqlpackage /a:Script /sf:db/AdvWorkFlow.dacpac /p:ExcludeObjectType=Users > db/AdvWorkFlow_NoSecurity.dacpac

    - name: Deploy Package on Test Environment
      run: |
        sqlpackage /a:Publish /sf:db/AdvWorkFlow_NoSecurity.dacpac /tsn:$DB_HOST,$DB_PORT /tdn:$DB_TARGET /tu:$DB_USERNAME /tp:$DB_PASSWORD /p:BlockOnPossibleDataLoss=False
